// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerconfig/v1alpha1"
	internal "github.com/stolostron/submariner-addon/pkg/client/submarinerconfig/applyconfiguration/internal"
	submarinerconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/client/submarinerconfig/applyconfiguration/submarinerconfig/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=submarineraddon.open-cluster-management.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("AWS"):
		return &submarinerconfigv1alpha1.AWSApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("Azure"):
		return &submarinerconfigv1alpha1.AzureApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GatewayConfig"):
		return &submarinerconfigv1alpha1.GatewayConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("GCP"):
		return &submarinerconfigv1alpha1.GCPApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("ManagedClusterInfo"):
		return &submarinerconfigv1alpha1.ManagedClusterInfoApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("RHOS"):
		return &submarinerconfigv1alpha1.RHOSApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubmarinerConfig"):
		return &submarinerconfigv1alpha1.SubmarinerConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubmarinerConfigSpec"):
		return &submarinerconfigv1alpha1.SubmarinerConfigSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubmarinerConfigStatus"):
		return &submarinerconfigv1alpha1.SubmarinerConfigStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubmarinerImagePullSpecs"):
		return &submarinerconfigv1alpha1.SubmarinerImagePullSpecsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubscriptionConfig"):
		return &submarinerconfigv1alpha1.SubscriptionConfigApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
