// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerconfig/v1alpha1"
	scheme "github.com/stolostron/submariner-addon/pkg/client/submarinerconfig/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// SubmarinerDiagnoseConfigsGetter has a method to return a SubmarinerDiagnoseConfigInterface.
// A group's client should implement this interface.
type SubmarinerDiagnoseConfigsGetter interface {
	SubmarinerDiagnoseConfigs(namespace string) SubmarinerDiagnoseConfigInterface
}

// SubmarinerDiagnoseConfigInterface has methods to work with SubmarinerDiagnoseConfig resources.
type SubmarinerDiagnoseConfigInterface interface {
	Create(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.CreateOptions) (*v1alpha1.SubmarinerDiagnoseConfig, error)
	Update(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.UpdateOptions) (*v1alpha1.SubmarinerDiagnoseConfig, error)
	UpdateStatus(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.UpdateOptions) (*v1alpha1.SubmarinerDiagnoseConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.SubmarinerDiagnoseConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SubmarinerDiagnoseConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubmarinerDiagnoseConfig, err error)
	SubmarinerDiagnoseConfigExpansion
}

// submarinerDiagnoseConfigs implements SubmarinerDiagnoseConfigInterface
type submarinerDiagnoseConfigs struct {
	client rest.Interface
	ns     string
}

// newSubmarinerDiagnoseConfigs returns a SubmarinerDiagnoseConfigs
func newSubmarinerDiagnoseConfigs(c *SubmarineraddonV1alpha1Client, namespace string) *submarinerDiagnoseConfigs {
	return &submarinerDiagnoseConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the submarinerDiagnoseConfig, and returns the corresponding submarinerDiagnoseConfig object, and an error if there is any.
func (c *submarinerDiagnoseConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	result = &v1alpha1.SubmarinerDiagnoseConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of SubmarinerDiagnoseConfigs that match those selectors.
func (c *submarinerDiagnoseConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubmarinerDiagnoseConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SubmarinerDiagnoseConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested submarinerDiagnoseConfigs.
func (c *submarinerDiagnoseConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a submarinerDiagnoseConfig and creates it.  Returns the server's representation of the submarinerDiagnoseConfig, and an error, if there is any.
func (c *submarinerDiagnoseConfigs) Create(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.CreateOptions) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	result = &v1alpha1.SubmarinerDiagnoseConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(submarinerDiagnoseConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a submarinerDiagnoseConfig and updates it. Returns the server's representation of the submarinerDiagnoseConfig, and an error, if there is any.
func (c *submarinerDiagnoseConfigs) Update(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.UpdateOptions) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	result = &v1alpha1.SubmarinerDiagnoseConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		Name(submarinerDiagnoseConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(submarinerDiagnoseConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *submarinerDiagnoseConfigs) UpdateStatus(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.UpdateOptions) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	result = &v1alpha1.SubmarinerDiagnoseConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		Name(submarinerDiagnoseConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(submarinerDiagnoseConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the submarinerDiagnoseConfig and deletes it. Returns an error if one occurs.
func (c *submarinerDiagnoseConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *submarinerDiagnoseConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched submarinerDiagnoseConfig.
func (c *submarinerDiagnoseConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	result = &v1alpha1.SubmarinerDiagnoseConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("submarinerdiagnoseconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
