// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SubmarinerDiagnoseConfigs returns a SubmarinerDiagnoseConfigInformer.
	SubmarinerDiagnoseConfigs() TypedSubmarinerDiagnoseConfigInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SubmarinerDiagnoseConfigs returns a TypedSubmarinerDiagnoseConfigInformer.
func (v *version) SubmarinerDiagnoseConfigs() TypedSubmarinerDiagnoseConfigInformer {
	return &submarinerDiagnoseConfigInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
