// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apissubmarinerdiagnoseconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerdiagnoseconfig/v1alpha1"
	versioned "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/clientset/versioned"
	internalinterfaces "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/informers/externalversions/internalinterfaces"
	submarinerdiagnoseconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/listers/submarinerdiagnoseconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SubmarinerDiagnoseConfigInformer provides access to a shared informer and lister for
// SubmarinerDiagnoseConfigs. Prefer using the type-safe variant (see [TypedSubmarinerDiagnoseConfigInformer]).
type SubmarinerDiagnoseConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() submarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfigLister
}

// TypedSubmarinerDiagnoseConfigInformer provides access to a shared informer and lister for
// SubmarinerDiagnoseConfigs, including the type-safe TypedInformer variant.
// It is a superset of SubmarinerDiagnoseConfigInformer.
type TypedSubmarinerDiagnoseConfigInformer interface {
	Informer() cache.SharedIndexInformer
	TypedInformer() SubmarinerDiagnoseConfigIndexInformer
	Lister() submarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfigLister
}

// SubmarinerDiagnoseConfigIndexInformer is a wrapper around the underlying [cache.SharedIndexInformer]
// with type-safe variants of several methods.
type SubmarinerDiagnoseConfigIndexInformer cache.TypedSharedIndexInformer[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig]

// SubmarinerDiagnoseConfigHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerFuncs] for SubmarinerDiagnoseConfig.
type SubmarinerDiagnoseConfigHandlerFuncs = cache.TypedResourceEventHandlerFuncs[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig]

// SubmarinerDiagnoseConfigDetailedHandlerFuncs is a specialization of [cache.TypedResourceEventHandlerDetailedFuncs] for SubmarinerDiagnoseConfig.
type SubmarinerDiagnoseConfigDetailedHandlerFuncs = cache.TypedResourceEventHandlerDetailedFuncs[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig]

// SubmarinerDiagnoseConfigFilteringHandler is a specialization of [cache.TypedFilteringResourceEventHandler] for SubmarinerDiagnoseConfig.
type SubmarinerDiagnoseConfigFilteringHandler = cache.TypedFilteringResourceEventHandler[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig]

// SubmarinerDiagnoseConfigIndexers is a specialization of [cache.TypedIndexers] for SubmarinerDiagnoseConfig.
type SubmarinerDiagnoseConfigIndexers = cache.TypedIndexers[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig]

// DeletedSubmarinerDiagnoseConfig is a specialization of [cache.DeletedObject] for SubmarinerDiagnoseConfig.
type DeletedSubmarinerDiagnoseConfig = cache.DeletedObject[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig]

type submarinerDiagnoseConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSubmarinerDiagnoseConfigInformer constructs a new informer for SubmarinerDiagnoseConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSubmarinerDiagnoseConfigInformer]).
func NewSubmarinerDiagnoseConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewSubmarinerDiagnoseConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers})
}

// NewTypedSubmarinerDiagnoseConfigInformer constructs a new informer for SubmarinerDiagnoseConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSubmarinerDiagnoseConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers SubmarinerDiagnoseConfigIndexers) SubmarinerDiagnoseConfigIndexInformer {
	return NewTypedSubmarinerDiagnoseConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers)})
}

// NewFilteredSubmarinerDiagnoseConfigInformer constructs a new informer for SubmarinerDiagnoseConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedFilteredSubmarinerDiagnoseConfigInformer]).
func NewFilteredSubmarinerDiagnoseConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return NewTypedSubmarinerDiagnoseConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: indexers, TweakListOptions: tweakListOptions})
}

// NewTypedFilteredSubmarinerDiagnoseConfigInformer constructs a new informer for SubmarinerDiagnoseConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedFilteredSubmarinerDiagnoseConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers SubmarinerDiagnoseConfigIndexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) SubmarinerDiagnoseConfigIndexInformer {
	return NewTypedSubmarinerDiagnoseConfigInformerWithOptions(client, namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.TypedIndexersToIndexers(indexers), TweakListOptions: tweakListOptions})
}

// NewSubmarinerDiagnoseConfigInformerWithOptions constructs a new informer for SubmarinerDiagnoseConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
// If you really need an independent one, prefer using the type-safe variant (see [NewTypedSubmarinerDiagnoseConfigInformerWithOptions]).
func NewSubmarinerDiagnoseConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) cache.SharedIndexInformer {
	return NewTypedSubmarinerDiagnoseConfigInformerWithOptions(client, namespace, options)
}

// NewTypedSubmarinerDiagnoseConfigInformerWithOptions constructs a new informer for SubmarinerDiagnoseConfig type with additional options.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTypedSubmarinerDiagnoseConfigInformerWithOptions(client versioned.Interface, namespace string, options internalinterfaces.InformerOptions) SubmarinerDiagnoseConfigIndexInformer {
	gvr := schema.GroupVersionResource{Group: "submarineraddon.open-cluster-management.io", Version: "v1alpha1", Resource: "submarinerdiagnoseconfigs"}
	identifier := options.InformerName.WithResource(gvr)
	tweakListOptions := options.TweakListOptions
	return cache.NewTypedSharedIndexInformer[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig](cache.NewSharedIndexInformerWithOptions(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerDiagnoseConfigs(namespace).List(context.Background(), opts)
			},
			WatchFunc: func(opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerDiagnoseConfigs(namespace).Watch(context.Background(), opts)
			},
			ListWithContextFunc: func(ctx context.Context, opts v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerDiagnoseConfigs(namespace).List(ctx, opts)
			},
			WatchFuncWithContext: func(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&opts)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerDiagnoseConfigs(namespace).Watch(ctx, opts)
			},
		}, client),
		&apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig{},
		cache.SharedIndexInformerOptions{
			ResyncPeriod: options.ResyncPeriod,
			Indexers:     options.Indexers,
			Identifier:   identifier,
		},
	))
}

func (f *submarinerDiagnoseConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewTypedSubmarinerDiagnoseConfigInformerWithOptions(client, f.namespace, internalinterfaces.InformerOptions{ResyncPeriod: resyncPeriod, Indexers: cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, InformerName: f.factory.InformerName(), TweakListOptions: f.tweakListOptions})
}

func (f *submarinerDiagnoseConfigInformer) Informer() cache.SharedIndexInformer {
	return f.TypedInformer()
}

func (f *submarinerDiagnoseConfigInformer) TypedInformer() SubmarinerDiagnoseConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig](f.factory.InformerFor(&apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig{}, f.defaultInformer))
}

func (f *submarinerDiagnoseConfigInformer) Lister() submarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfigLister {
	return submarinerdiagnoseconfigv1alpha1.NewSubmarinerDiagnoseConfigLister(f.Informer().GetIndexer())
}

// ToTypedSubmarinerDiagnoseConfigInformer converts an untyped informer into a TypedSubmarinerDiagnoseConfigInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SubmarinerDiagnoseConfig. If that is not the case, calling type-safe methods of the returned
// TypedSubmarinerDiagnoseConfigInformer leads to runtime panics. A safer alternative is to pass
// around a TypedSubmarinerDiagnoseConfigInformer instances that was obtained from a
// SharedInformerFactory.
func ToTypedSubmarinerDiagnoseConfigInformer(informer SubmarinerDiagnoseConfigInformer) TypedSubmarinerDiagnoseConfigInformer {
	if informer, ok := informer.(TypedSubmarinerDiagnoseConfigInformer); ok {
		return informer
	}
	return &submarinerDiagnoseConfigTypedInformerAdapter{informer}
}

type submarinerDiagnoseConfigTypedInformerAdapter struct {
	SubmarinerDiagnoseConfigInformer
}

func (a *submarinerDiagnoseConfigTypedInformerAdapter) TypedInformer() SubmarinerDiagnoseConfigIndexInformer {
	return cache.NewTypedSharedIndexInformer[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig](a.Informer())
}

// ToSubmarinerDiagnoseConfigIndexInformer converts an untyped informer into a SubmarinerDiagnoseConfigIndexInformer.
//
// WARNING: this conversion is only safe if the informer handles objects of type
// *SubmarinerDiagnoseConfig. If that is not the case, calling type-safe methods of the returned
// SubmarinerDiagnoseConfigIndexInformer leads to runtime panics. A safer alternative is to pass
// around a SubmarinerDiagnoseConfigIndexInformer instances that was obtained from a
// SharedInformerFactory.
func ToSubmarinerDiagnoseConfigIndexInformer(informer cache.SharedIndexInformer) SubmarinerDiagnoseConfigIndexInformer {
	if informer, ok := informer.(SubmarinerDiagnoseConfigIndexInformer); ok {
		return informer
	}
	return cache.NewTypedSharedIndexInformer[*apissubmarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfig](informer)
}
