---
run:
  skip-dirs:
    - pkg/cloud
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  govet:
    enable:
      - fieldalignment
  lll:
    line-length: 140
  nlreturn:
    block-size: 2
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    # - cyclop # This is equivalent to gocyclo
    - deadcode
    - depguard
    - dogsled
    # - dupl # TODO: Fix and enable
    - durationcheck
    - errcheck
    # - errname # TODO: Not supported with our version of golangci-lint
    - errorlint
    - exhaustive
    # - exhaustivestruct # Not recommended for general use - meant to be used only for special cases
    - exportloopref
    # - forbidigo # We don't forbid any statements
    # - forcetypeassert # TODO: Fix and enable
    # - funlen # gocyclo is enabled which is generally a better metric than simply LOC
    - gci
    # - gochecknoglobal # We don't want to forbid global variable constants
    # - gochecknoinits # We have valid uses for init functions
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox # Let's not forbid inline TODOs, FIXMEs et al
    # - goerr113 # TODO: Fix and enable
    - gofmt
    - gofumpt
    # - goheader # We do license header linting another way
    - goimports
    # - golint # Deprecated since v1.41.0
    # - gomnd # It doesn't seem useful in general to enforce constants for all numeric value
    # - gomoddirectives # We don't want to forbid the 'replace' directive
    # - gomodguard # We don't block any modules
    # - goprintffuncname # This doesn't seem useful at all
    - gosec
    - gosimple
    - govet
    # - ifshort # This is a style preference and doesn't seem compelling
    # - importas # Not supported with our version of golangci-lint
    - ineffassign
    # - interfacer # Deprecated since v1.38.0
    - lll
    - makezero
    # - maligned # Deprecated since v1.38.0
    - misspell
    - nakedret
    # - nestif # This calculates cognitive complexity but we're doing that elsewhere
    # - nilerr # TODO: Fix and enable
    - nlreturn
    # - noctx # We don't send HTTP requests
    - nolintlint
    # - paralleltest # Not relevant for Ginkgo UT
    - prealloc
    - predeclared
    # - promlinter # Not supported with our version of golangci-lint
    # - revive # TODO: Do we want this?
    # - rowserrcheck # We don't use SQL
    # - scopelint # Deprecated since v1.39.0
    # - sqlclosecheck # We don't use SQL
    - staticcheck
    - structcheck
    - stylecheck
    # - tagliatelle # Inconsistent with stylecheck and not as good
    # - testpackage # TODO: Fix and enable
    # - thelper # Not relevant for our Ginkgo UTs
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    # - wastedassign # Not supported with our version of golangci-lint
    - whitespace
    # - wrapcheck # Fix and enable
    - wsl
issues:
  exclude-rules:
    # Separating explicit var declarations by blank lines seems excessive.
    - linters:
        - wsl
      text: "declarations should never be cuddled"

    # This rule incorrectly flags code where two logically-related lines are
    # followed by an if conditional to check their err return.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before if statement"

    # This rule incorrectly flags code where two logically-related lines are
    # used to create vars that are consumed in a loop.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before range statement"

    # Allow dot imports for `fake` directory and e2e tests
    - linters:
        - stylecheck
      text: "ST1001: "
      path: /fake

    - linters:
        - stylecheck
      text: "ST1001: "
      path: test

    # Ignore pointer bytes in struct alignment tests (this is a very
    # minor optimisation)
    - linters:
        - govet
      text: "pointer bytes could be"

    # Ignore long line non-compliance warnings in auto-generated files
    - linters:
        - lll
      path: "pkg/apis/submarinerconfig/v1alpha1/zz_generated.swagger_doc_generated.go"

    # Ignore any failures in auto-generated files
    - linters:
        - stylecheck
        - godot
      path: "pkg/apis/submarinerconfig/v1alpha1/zz_generated.swagger_doc_generated.go"
