---
run:
  skip-dirs:
    - pkg/cloud
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 20
  govet:
    enable:
      - fieldalignment
  lll:
    line-length: 140
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    # - cyclop # TODO: Do we want this?
    - deadcode
    - depguard
    - dogsled
    # - dupl # TODO: Fix and enable
    - durationcheck
    - errcheck
    # - errname # Not supported with our version of golangci-lint
    - errorlint
    - exhaustive
    # - exhaustivestruct # TODO: Do we want this?
    - exportloopref
    # - forbidigo # We don't forbid any statements
    # - forcetypeassert # TODO: Fix and enable
    # - funlen # TODO: Do we want this?
    - gci
    # - gochecknoglobal # TODO: Do we want this?
    # - gochecknoinits # TODO: Do we want this?
    # - gocognit # Actually runs revive linter
    - goconst
    - gocritic
    # - gocyclo # TODO: Do we want this?
    # - godot # TODO: Do we want this?
    # - godox # TODO: Do we want this?
    # - goerr113 # TODO: Fix and enable
    - gofmt
    - gofumpt
    # - goheader # We do license header linting another way
    - goimports
    # - golint # Deprecated since v1.41.0
    # - gomnd # TODO: Do we want this?
    # - gomoddirectives # Actually runs revive linter
    # - gomodguard # We don't block any modules
    # - goprintffuncname # This doesn't seem useful at all
    - gosec
    - gosimple
    - govet
    # - ifshort # TODO: Fix and enable
    # - importas # Not supported with our version of golangci-lint
    - ineffassign
    # - interfacer # Deprecated since v1.38.0
    - lll
    - makezero
    # - maligned # Deprecated since v1.38.0
    - misspell
    - nakedret
    # - nestif # Actually runs revive linter
    # - nilerr # TODO: Fix and enable
    - nlreturn
    # - noctx # We don't send HTTP requests
    - nolintlint
    # - paralleltest # TODO: Do we want this?
    - prealloc
    - predeclared
    # - promlinter # Not supported with our version of golangci-lint
    # - revive # TODO: Do we want this?
    # - rowserrcheck # We don't use SQL
    # - scopelint # Deprecated since v1.39.0
    # - sqlclosecheck # We don't use SQL
    - staticcheck
    - structcheck
    - stylecheck
    # - tagliatelle # TODO: Do we want this?
    # - testpackage # TODO: Fix and enable
    # - thelper # Not relevant for our Ginkgo UTs
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    # - wastedassign # Not supported with our version of golangci-lint
    - whitespace
    # - wrapcheck # TODO: Do we want this?
    - wsl
issues:
  exclude-rules:
    # Separating explicit var declarations by blank lines seems excessive.
    - linters:
        - wsl
      text: "declarations should never be cuddled"

    # This rule incorrectly flags code where two logically-related lines are
    # followed by an if conditional to check their err return.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before if statement"

    # This rule incorrectly flags code where two logically-related lines are
    # used to create vars that are consumed in a loop.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before range statement"

    # Allow dot imports for `fake` directory and e2e tests
    - linters:
        - stylecheck
      text: "ST1001: "
      path: /fake

    - linters:
        - stylecheck
      text: "ST1001: "
      path: test

    # Ignore pointer bytes in struct alignment tests (this is a very
    # minor optimisation)
    - linters:
        - govet
      text: "pointer bytes could be"

    # Ignore long line non-compliance warnings in auto-generated files
    - linters:
        - lll
      path: "pkg/apis/submarinerconfig/v1alpha1/zz_generated.swagger_doc_generated.go"

    # Ignore underscores in var names in auto-generated files
    - linters:
        - stylecheck
      path: "pkg/apis/submarinerconfig/v1alpha1/zz_generated.swagger_doc_generated.go"

    # This needs to be changed in the main submariner-io/submariner repo first
    - linters:
        - stylecheck
      text: "struct field InfraId should be InfraID"
