---
run:
linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - unnamedResult
  gocyclo:
    min-complexity: 15
  govet:
    enable:
      - fieldalignment
  lll:
    line-length: 140
  wsl:
    # Separating explicit var declarations by blank lines seems excessive.
    allow-cuddle-declarations: true
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    # - cyclop # This is equivalent to gocyclo
    - decorder
    # - depguard # depguard now denies by default, it should only be enabled if we actually use it
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errorlint
    - errname
    # - execinquery # No SQL
    - exhaustive
    # - exhauststruct # Not recommended for general use - meant to be used only for special cases
    # - forbidigo # We don't forbid any statements
    # - forcetypeassert # There are many unchecked type assertions that would be the result of a programming error so the
    #                     reasonable recourse would be to panic anyway if checked so this doesn't seem useful
    # - funlen # gocyclo is enabled which is generally a better metric than simply LOC.
    - gci
    - ginkgolinter
    # - gochecknoglobals # We don't want to forbid global variable constants
    # - gochecknoinits # We use init functions for valid reasons
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # - godox #  Let's not forbid inline TODOs, FIXMEs et al
    - gofmt
    - gofumpt
    # - goheader # We do license header linting another way
    - goimports
    # - gomnd # It doesn't seem useful in general to enforce constants for all numeric values
    # - gomoddirectives # We don't want to forbid the 'replace' directive
    # - gomodguard # We don't block any modules
    # - goprintffuncname # This doesn't seem useful at all
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    # - interfacebloat # We track complexity elsewhere
    # - ireturn # The argument to always "Return Concrete Types" doesn't seem compelling. It is perfectly valid to return
    #             an interface to avoid exposing the entire underlying struct
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - nakedret
    # - nestif # This calculates cognitive complexity but we're doing that elsewhere
    - nilerr
    - nilnil
    # - nlreturn # This is reasonable with a block-size of 2 but setting it above isn't honored
    # - noctx # We don't send HTTP requests
    - nolintlint
    # - nonamedreturns # We don't forbid named returns
    - nosprintfhostport
    # - paralleltest # Not relevant for Ginkgo UTs
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    # - rowserrcheck # We don't use SQL
    # - sqlclosecheck # We don't use SQL
    - staticcheck
    - stylecheck
    # - tagliatelle # Inconsistent with stylecheck and not as good
    # - tenv # Not relevant for our Ginkgo UTs
    - testableexamples
    - testpackage
    # - thelper # Not relevant for our Ginkgo UTs
    # - tparallel # Not relevant for our Ginkgo UTs
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    # - varnamelen # It doesn't seem necessary to enforce a minimum variable name length
    - wastedassign
    - whitespace
    # - wrapcheck # Fix and enable
    - wsl
issues:
  exclude-rules:
    # Separating explicit var declarations by blank lines seems excessive.
    - linters:
        - wsl
      text: "declarations should never be cuddled"

    # This rule incorrectly flags code where two logically-related lines are
    # followed by an if conditional to check their err return.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before if statement"

    # This rule incorrectly flags code where two logically-related lines are
    # used to create vars that are consumed in a loop.
    - linters:
        - wsl
      text: "only one cuddle assignment allowed before range statement"

    # Allow dot-imports for Gomega BDD directives per idiomatic Gomega
    - linters:
        - revive
        - stylecheck
      text: "dot imports"
      source: "gomega"

    # Allow dot-imports for Ginkgo BDD directives per idiomatic Ginkgo
    - linters:
        - revive
        - stylecheck
      text: "dot imports"
      source: "ginkgo"

    # Ignore pointer bytes in struct alignment tests (this is a very
    # minor optimisation)
    - linters:
        - govet
      text: "pointer bytes could be"

    # Ignore any failures in auto-generated files
    - path: swagger_doc_generated\.go
      linters:
        - lll
        - stylecheck
        - godot
        - revive

    # Full text of the error is "do not define dynamic errors, use wrapped static errors instead". See
    # https://github.com/Djarvur/go-err113/issues/10 for an interesting discussion of this error. While there are cases
    # where wrapped sentinel errors are useful, it seems a bit pedantic to force that pattern in all cases.
    - linters:
        - err113
      text: "do not define dynamic errors"

