FROM brew.registry.redhat.io/rh-osbs/openshift-golang-builder:v1.25 AS builder
WORKDIR /go/src/github.com/stolostron/submariner-addon
COPY . .
ENV GO_PACKAGE github.com/stolostron/submariner-addon
RUN make golangci-lint-run
