kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:submariner-addon:agent
  namespace: {{ .ClusterName }}
rules:
# Allow submariner-addon agent to operator managedclusteraddons on the hub cluster
- apiGroups: ["addon.open-cluster-management.io"]
  resources: ["managedclusteraddons"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["addon.open-cluster-management.io"]
  resources: ["managedclusteraddons/finalizers"]
  verbs: ["update"]
- apiGroups: ["addon.open-cluster-management.io"]
  resources: ["managedclusteraddons/status"]
  verbs: ["patch", "update"]
# Allow submariner-addon agent to operator submarinerconfigs on the hub cluster
- apiGroups: ["submarineraddon.open-cluster-management.io"]
  resources: ["submarinerconfigs"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["submarineraddon.open-cluster-management.io"]
  resources: ["submarinerconfigs/finalizers"]
  verbs: ["update"]
- apiGroups: ["submarineraddon.open-cluster-management.io"]
  resources: ["submarinerconfigs/status"]
  verbs: ["patch", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
