// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apissubmarinerconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerconfig/v1alpha1"
	versioned "github.com/stolostron/submariner-addon/pkg/client/submarinerconfig/clientset/versioned"
	internalinterfaces "github.com/stolostron/submariner-addon/pkg/client/submarinerconfig/informers/externalversions/internalinterfaces"
	submarinerconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/client/submarinerconfig/listers/submarinerconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SubmarinerConfigInformer provides access to a shared informer and lister for
// SubmarinerConfigs.
type SubmarinerConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() submarinerconfigv1alpha1.SubmarinerConfigLister
}

type submarinerConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSubmarinerConfigInformer constructs a new informer for SubmarinerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSubmarinerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSubmarinerConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSubmarinerConfigInformer constructs a new informer for SubmarinerConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSubmarinerConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerConfigs(namespace).List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerConfigs(namespace).Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerConfigs(namespace).List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SubmarineraddonV1alpha1().SubmarinerConfigs(namespace).Watch(ctx, options)
			},
		},
		&apissubmarinerconfigv1alpha1.SubmarinerConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *submarinerConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSubmarinerConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *submarinerConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apissubmarinerconfigv1alpha1.SubmarinerConfig{}, f.defaultInformer)
}

func (f *submarinerConfigInformer) Lister() submarinerconfigv1alpha1.SubmarinerConfigLister {
	return submarinerconfigv1alpha1.NewSubmarinerConfigLister(f.Informer().GetIndexer())
}
