// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SubmarinerConfigListerExpansion allows custom methods to be added to
// SubmarinerConfigLister.
type SubmarinerConfigListerExpansion interface{}

// SubmarinerConfigNamespaceListerExpansion allows custom methods to be added to
// SubmarinerConfigNamespaceLister.
type SubmarinerConfigNamespaceListerExpansion interface{}

// SubmarinerDiagnoseConfigListerExpansion allows custom methods to be added to
// SubmarinerDiagnoseConfigLister.
type SubmarinerDiagnoseConfigListerExpansion interface{}

// SubmarinerDiagnoseConfigNamespaceListerExpansion allows custom methods to be added to
// SubmarinerDiagnoseConfigNamespaceLister.
type SubmarinerDiagnoseConfigNamespaceListerExpansion interface{}
