// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SubmarinerConfigListerExpansion allows custom methods to be added to
// SubmarinerConfigLister.
type SubmarinerConfigListerExpansion interface{}

// SubmarinerConfigNamespaceListerExpansion allows custom methods to be added to
// SubmarinerConfigNamespaceLister.
type SubmarinerConfigNamespaceListerExpansion interface{}
