// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfiguration

import (
	v1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerdiagnoseconfig/v1alpha1"
	internal "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/applyconfiguration/internal"
	submarinerdiagnoseconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/applyconfiguration/submarinerdiagnoseconfig/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=submarineraddon.open-cluster-management.io, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithKind("FirewallOptions"):
		return &submarinerdiagnoseconfigv1alpha1.FirewallOptionsApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("FirewallStatus"):
		return &submarinerdiagnoseconfigv1alpha1.FirewallStatusApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubmarinerDiagnoseConfig"):
		return &submarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfigApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubmarinerDiagnoseSpec"):
		return &submarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseSpecApplyConfiguration{}
	case v1alpha1.SchemeGroupVersion.WithKind("SubmarinerDiagnoseStatus"):
		return &submarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseStatusApplyConfiguration{}

	}
	return nil
}

func NewTypeConverter(scheme *runtime.Scheme) managedfields.TypeConverter {
	return managedfields.NewSchemeTypeConverter(scheme, internal.Parser())
}
