// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	submarinerdiagnoseconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerdiagnoseconfig/v1alpha1"
)

// FirewallStatusApplyConfiguration represents a declarative configuration of the FirewallStatus type for use
// with apply.
type FirewallStatusApplyConfiguration struct {
	Metrics     *submarinerdiagnoseconfigv1alpha1.FirewallPortStatus `json:"metricsStatus,omitempty"`
	VxlanTunnel *submarinerdiagnoseconfigv1alpha1.FirewallPortStatus `json:"vxlanTunnel,omitempty"`
	IPSecTunnel *submarinerdiagnoseconfigv1alpha1.FirewallPortStatus `json:"IPSecTunnel,omitempty"`
}

// FirewallStatusApplyConfiguration constructs a declarative configuration of the FirewallStatus type for use with
// apply.
func FirewallStatus() *FirewallStatusApplyConfiguration {
	return &FirewallStatusApplyConfiguration{}
}

// WithMetrics sets the Metrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metrics field is set to the value of the last call.
func (b *FirewallStatusApplyConfiguration) WithMetrics(value submarinerdiagnoseconfigv1alpha1.FirewallPortStatus) *FirewallStatusApplyConfiguration {
	b.Metrics = &value
	return b
}

// WithVxlanTunnel sets the VxlanTunnel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VxlanTunnel field is set to the value of the last call.
func (b *FirewallStatusApplyConfiguration) WithVxlanTunnel(value submarinerdiagnoseconfigv1alpha1.FirewallPortStatus) *FirewallStatusApplyConfiguration {
	b.VxlanTunnel = &value
	return b
}

// WithIPSecTunnel sets the IPSecTunnel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPSecTunnel field is set to the value of the last call.
func (b *FirewallStatusApplyConfiguration) WithIPSecTunnel(value submarinerdiagnoseconfigv1alpha1.FirewallPortStatus) *FirewallStatusApplyConfiguration {
	b.IPSecTunnel = &value
	return b
}
