// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FirewallOptionsApplyConfiguration represents a declarative configuration of the FirewallOptions type for use
// with apply.
type FirewallOptionsApplyConfiguration struct {
	InterCluster             *bool   `json:"interCluster,omitempty"`
	IntraCluster             *bool   `json:"intraCluster,omitempty"`
	Metrics                  *bool   `json:"metrics,omitempty"`
	RemoteCluster            *string `json:"remoteCluster,omitempty"`
	RemoteK8sAPIServer       *string `json:"remoteK8sAPIServer,omitempty"`
	RemoteK8sAPIServerToken  *string `json:"remoteK8sAPIServerToken,omitempty"`
	RemoteK8sCA              *string `json:"remoteK8sCA,omitempty"`
	RemoteK8sSecret          *string `json:"remoteK8sSecret,omitempty"`
	RemoteK8sRemoteNamespace *string `json:"remoteK8sRemoteNamespace,omitempty"`
}

// FirewallOptionsApplyConfiguration constructs a declarative configuration of the FirewallOptions type for use with
// apply.
func FirewallOptions() *FirewallOptionsApplyConfiguration {
	return &FirewallOptionsApplyConfiguration{}
}

// WithInterCluster sets the InterCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InterCluster field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithInterCluster(value bool) *FirewallOptionsApplyConfiguration {
	b.InterCluster = &value
	return b
}

// WithIntraCluster sets the IntraCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IntraCluster field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithIntraCluster(value bool) *FirewallOptionsApplyConfiguration {
	b.IntraCluster = &value
	return b
}

// WithMetrics sets the Metrics field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metrics field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithMetrics(value bool) *FirewallOptionsApplyConfiguration {
	b.Metrics = &value
	return b
}

// WithRemoteCluster sets the RemoteCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteCluster field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithRemoteCluster(value string) *FirewallOptionsApplyConfiguration {
	b.RemoteCluster = &value
	return b
}

// WithRemoteK8sAPIServer sets the RemoteK8sAPIServer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteK8sAPIServer field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithRemoteK8sAPIServer(value string) *FirewallOptionsApplyConfiguration {
	b.RemoteK8sAPIServer = &value
	return b
}

// WithRemoteK8sAPIServerToken sets the RemoteK8sAPIServerToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteK8sAPIServerToken field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithRemoteK8sAPIServerToken(value string) *FirewallOptionsApplyConfiguration {
	b.RemoteK8sAPIServerToken = &value
	return b
}

// WithRemoteK8sCA sets the RemoteK8sCA field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteK8sCA field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithRemoteK8sCA(value string) *FirewallOptionsApplyConfiguration {
	b.RemoteK8sCA = &value
	return b
}

// WithRemoteK8sSecret sets the RemoteK8sSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteK8sSecret field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithRemoteK8sSecret(value string) *FirewallOptionsApplyConfiguration {
	b.RemoteK8sSecret = &value
	return b
}

// WithRemoteK8sRemoteNamespace sets the RemoteK8sRemoteNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RemoteK8sRemoteNamespace field is set to the value of the last call.
func (b *FirewallOptionsApplyConfiguration) WithRemoteK8sRemoteNamespace(value string) *FirewallOptionsApplyConfiguration {
	b.RemoteK8sRemoteNamespace = &value
	return b
}
