// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubmarinerDiagnoseSpecApplyConfiguration represents a declarative configuration of the SubmarinerDiagnoseSpec type for use
// with apply.
//
// SubmarinerDiagnoseSpec defines the desired configuration to run SubmarinerDiagnose.
type SubmarinerDiagnoseSpecApplyConfiguration struct {
	All             *bool                              `json:"all,omitempty"`
	CNI             *bool                              `json:"CNI,omitempty"`
	Connections     *bool                              `json:"connections,omitempty"`
	Deployment      *bool                              `json:"deployment,omitempty"`
	Firewall        *bool                              `json:"firewall,omitempty"`
	GatherLogs      *bool                              `json:"gatherLogs,omitempty"`
	K8sVersion      *bool                              `json:"k8sVersion,omitempty"`
	KubeProxyMode   *bool                              `json:"kubeProxyMode,omitempty"`
	FirewallOptions *FirewallOptionsApplyConfiguration `json:"firewallOptions,omitempty"`
}

// SubmarinerDiagnoseSpecApplyConfiguration constructs a declarative configuration of the SubmarinerDiagnoseSpec type for use with
// apply.
func SubmarinerDiagnoseSpec() *SubmarinerDiagnoseSpecApplyConfiguration {
	return &SubmarinerDiagnoseSpecApplyConfiguration{}
}

// WithAll sets the All field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the All field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithAll(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.All = &value
	return b
}

// WithCNI sets the CNI field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CNI field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithCNI(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.CNI = &value
	return b
}

// WithConnections sets the Connections field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Connections field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithConnections(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.Connections = &value
	return b
}

// WithDeployment sets the Deployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Deployment field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithDeployment(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.Deployment = &value
	return b
}

// WithFirewall sets the Firewall field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Firewall field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithFirewall(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.Firewall = &value
	return b
}

// WithGatherLogs sets the GatherLogs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GatherLogs field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithGatherLogs(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.GatherLogs = &value
	return b
}

// WithK8sVersion sets the K8sVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the K8sVersion field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithK8sVersion(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.K8sVersion = &value
	return b
}

// WithKubeProxyMode sets the KubeProxyMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeProxyMode field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithKubeProxyMode(value bool) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.KubeProxyMode = &value
	return b
}

// WithFirewallOptions sets the FirewallOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirewallOptions field is set to the value of the last call.
func (b *SubmarinerDiagnoseSpecApplyConfiguration) WithFirewallOptions(value *FirewallOptionsApplyConfiguration) *SubmarinerDiagnoseSpecApplyConfiguration {
	b.FirewallOptions = value
	return b
}
