// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SubmarinerDiagnoseStatusApplyConfiguration represents a declarative configuration of the SubmarinerDiagnoseStatus type for use
// with apply.
//
// SubmarinerDiagnoseStatus defines the observed result of SubmarinerDiagnose.
type SubmarinerDiagnoseStatusApplyConfiguration struct {
	Conditions     []v1.ConditionApplyConfiguration  `json:"conditions,omitempty"`
	K8sVersion     *string                           `json:"k8sVersion,omitempty"`
	CNIType        *string                           `json:"cniType,omitempty"`
	KubeProxyMode  *bool                             `json:"kubeProxyMode,omitempty"`
	FirewallStatus *FirewallStatusApplyConfiguration `json:"firewallStatus,omitempty"`
}

// SubmarinerDiagnoseStatusApplyConfiguration constructs a declarative configuration of the SubmarinerDiagnoseStatus type for use with
// apply.
func SubmarinerDiagnoseStatus() *SubmarinerDiagnoseStatusApplyConfiguration {
	return &SubmarinerDiagnoseStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SubmarinerDiagnoseStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SubmarinerDiagnoseStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithK8sVersion sets the K8sVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the K8sVersion field is set to the value of the last call.
func (b *SubmarinerDiagnoseStatusApplyConfiguration) WithK8sVersion(value string) *SubmarinerDiagnoseStatusApplyConfiguration {
	b.K8sVersion = &value
	return b
}

// WithCNIType sets the CNIType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CNIType field is set to the value of the last call.
func (b *SubmarinerDiagnoseStatusApplyConfiguration) WithCNIType(value string) *SubmarinerDiagnoseStatusApplyConfiguration {
	b.CNIType = &value
	return b
}

// WithKubeProxyMode sets the KubeProxyMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KubeProxyMode field is set to the value of the last call.
func (b *SubmarinerDiagnoseStatusApplyConfiguration) WithKubeProxyMode(value bool) *SubmarinerDiagnoseStatusApplyConfiguration {
	b.KubeProxyMode = &value
	return b
}

// WithFirewallStatus sets the FirewallStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FirewallStatus field is set to the value of the last call.
func (b *SubmarinerDiagnoseStatusApplyConfiguration) WithFirewallStatus(value *FirewallStatusApplyConfiguration) *SubmarinerDiagnoseStatusApplyConfiguration {
	b.FirewallStatus = value
	return b
}
