// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SubmarinerDiagnoseConfigListerExpansion allows custom methods to be added to
// SubmarinerDiagnoseConfigLister.
type SubmarinerDiagnoseConfigListerExpansion interface{}

// SubmarinerDiagnoseConfigNamespaceListerExpansion allows custom methods to be added to
// SubmarinerDiagnoseConfigNamespaceLister.
type SubmarinerDiagnoseConfigNamespaceListerExpansion interface{}
