// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AWSApplyConfiguration represents a declarative configuration of the AWS type for use
// with apply.
type AWSApplyConfiguration struct {
	// InstanceType represents the Amazon Web Services EC2 instance type of the gateway node that will be
	// created on the managed cluster.
	// The default value is `m5n.large`.
	InstanceType *string `json:"instanceType,omitempty"`
}

// AWSApplyConfiguration constructs a declarative configuration of the AWS type for use with
// apply.
func AWS() *AWSApplyConfiguration {
	return &AWSApplyConfiguration{}
}

// WithInstanceType sets the InstanceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceType field is set to the value of the last call.
func (b *AWSApplyConfiguration) WithInstanceType(value string) *AWSApplyConfiguration {
	b.InstanceType = &value
	return b
}
