// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AzureApplyConfiguration represents a declarative configuration of the Azure type for use
// with apply.
type AzureApplyConfiguration struct {
	// InstanceType represents the Azure Cloud Platform instance type of the gateway node that will be
	// created on the managed cluster.
	// The default value is `Standard_F4s_v2`.
	InstanceType *string `json:"instanceType,omitempty"`
}

// AzureApplyConfiguration constructs a declarative configuration of the Azure type for use with
// apply.
func Azure() *AzureApplyConfiguration {
	return &AzureApplyConfiguration{}
}

// WithInstanceType sets the InstanceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceType field is set to the value of the last call.
func (b *AzureApplyConfiguration) WithInstanceType(value string) *AzureApplyConfiguration {
	b.InstanceType = &value
	return b
}
