// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GatewayConfigApplyConfiguration represents a declarative configuration of the GatewayConfig type for use
// with apply.
type GatewayConfigApplyConfiguration struct {
	// AWS represents the configuration for Amazon Web Services.
	// If the platform of managed cluster is not Amazon Web Services, this field will be ignored.
	*AWSApplyConfiguration `json:"aws,omitempty"`
	// GCP represents the configuration for Google Cloud Platform.
	// If the platform of managed cluster is not Google Cloud Platform, this field will be ignored.
	*GCPApplyConfiguration `json:"gcp,omitempty"`
	// Azure represents the configuration for Azure Cloud Platform.
	// If the platform of managed cluster is not Azure Cloud Platform, this field will be ignored.
	*AzureApplyConfiguration `json:"azure,omitempty"`
	// RHOS represents the configuration for Redhat Openstack Platform.
	// If the platform of managed cluster is not Redhat Openstack Platform, this field will be ignored.
	*RHOSApplyConfiguration `json:"rhos,omitempty"`
	// Gateways represents the count of worker nodes that will be used to deploy the Submariner gateway
	// component on the managed cluster. The default value is 1, if the value is greater than 1, the
	// Submariner gateway HA will be enabled automatically.
	Gateways *int `json:"gateways,omitempty"`
}

// GatewayConfigApplyConfiguration constructs a declarative configuration of the GatewayConfig type for use with
// apply.
func GatewayConfig() *GatewayConfigApplyConfiguration {
	return &GatewayConfigApplyConfiguration{}
}

// WithInstanceType sets the InstanceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceType field is set to the value of the last call.
func (b *GatewayConfigApplyConfiguration) WithInstanceType(value string) *GatewayConfigApplyConfiguration {
	b.ensureAWSApplyConfigurationExists()
	b.AWSApplyConfiguration.InstanceType = &value
	return b
}

func (b *GatewayConfigApplyConfiguration) ensureAWSApplyConfigurationExists() {
	if b.AWSApplyConfiguration == nil {
		b.AWSApplyConfiguration = &AWSApplyConfiguration{}
	}
}

func (b *GatewayConfigApplyConfiguration) ensureGCPApplyConfigurationExists() {
	if b.GCPApplyConfiguration == nil {
		b.GCPApplyConfiguration = &GCPApplyConfiguration{}
	}
}

func (b *GatewayConfigApplyConfiguration) ensureAzureApplyConfigurationExists() {
	if b.AzureApplyConfiguration == nil {
		b.AzureApplyConfiguration = &AzureApplyConfiguration{}
	}
}

func (b *GatewayConfigApplyConfiguration) ensureRHOSApplyConfigurationExists() {
	if b.RHOSApplyConfiguration == nil {
		b.RHOSApplyConfiguration = &RHOSApplyConfiguration{}
	}
}

// WithGateways sets the Gateways field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateways field is set to the value of the last call.
func (b *GatewayConfigApplyConfiguration) WithGateways(value int) *GatewayConfigApplyConfiguration {
	b.Gateways = &value
	return b
}
