// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// GCPApplyConfiguration represents a declarative configuration of the GCP type for use
// with apply.
type GCPApplyConfiguration struct {
	// InstanceType represents the Google Cloud Platform instance type of the gateway node that will be
	// created on the managed cluster.
	// The default value is `n1-standard-4`.
	InstanceType *string `json:"instanceType,omitempty"`
}

// GCPApplyConfiguration constructs a declarative configuration of the GCP type for use with
// apply.
func GCP() *GCPApplyConfiguration {
	return &GCPApplyConfiguration{}
}

// WithInstanceType sets the InstanceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceType field is set to the value of the last call.
func (b *GCPApplyConfiguration) WithInstanceType(value string) *GCPApplyConfiguration {
	b.InstanceType = &value
	return b
}
