// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ManagedClusterInfoApplyConfiguration represents a declarative configuration of the ManagedClusterInfo type for use
// with apply.
type ManagedClusterInfoApplyConfiguration struct {
	// ClusterName represents the name of the managed cluster.
	ClusterName *string `json:"clusterName,omitempty"`
	// Vendor represents the kubernetes vendor of the managed cluster.
	Vendor *string `json:"vendor,omitempty"`
	// Platform represents the cloud provider of the managed cluster.
	Platform *string `json:"platform,omitempty"`
	// Region represents the cloud region of the managed cluster.
	Region *string `json:"region,omitempty"`
	// InfraId represents the infrastructure id of the managed cluster.
	InfraID *string `json:"infraId,omitempty"`
	// VendorVersion represents k8s vendor version of the managed cluster.
	VendorVersion *string `json:"vendorVersion,omitempty"`
	// NetworkType represents the network type (cni) of the managed cluster.
	NetworkType *string `json:"networkType,omitempty"`
}

// ManagedClusterInfoApplyConfiguration constructs a declarative configuration of the ManagedClusterInfo type for use with
// apply.
func ManagedClusterInfo() *ManagedClusterInfoApplyConfiguration {
	return &ManagedClusterInfoApplyConfiguration{}
}

// WithClusterName sets the ClusterName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterName field is set to the value of the last call.
func (b *ManagedClusterInfoApplyConfiguration) WithClusterName(value string) *ManagedClusterInfoApplyConfiguration {
	b.ClusterName = &value
	return b
}

// WithVendor sets the Vendor field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Vendor field is set to the value of the last call.
func (b *ManagedClusterInfoApplyConfiguration) WithVendor(value string) *ManagedClusterInfoApplyConfiguration {
	b.Vendor = &value
	return b
}

// WithPlatform sets the Platform field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Platform field is set to the value of the last call.
func (b *ManagedClusterInfoApplyConfiguration) WithPlatform(value string) *ManagedClusterInfoApplyConfiguration {
	b.Platform = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *ManagedClusterInfoApplyConfiguration) WithRegion(value string) *ManagedClusterInfoApplyConfiguration {
	b.Region = &value
	return b
}

// WithInfraID sets the InfraID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InfraID field is set to the value of the last call.
func (b *ManagedClusterInfoApplyConfiguration) WithInfraID(value string) *ManagedClusterInfoApplyConfiguration {
	b.InfraID = &value
	return b
}

// WithVendorVersion sets the VendorVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VendorVersion field is set to the value of the last call.
func (b *ManagedClusterInfoApplyConfiguration) WithVendorVersion(value string) *ManagedClusterInfoApplyConfiguration {
	b.VendorVersion = &value
	return b
}

// WithNetworkType sets the NetworkType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NetworkType field is set to the value of the last call.
func (b *ManagedClusterInfoApplyConfiguration) WithNetworkType(value string) *ManagedClusterInfoApplyConfiguration {
	b.NetworkType = &value
	return b
}
