// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RHOSApplyConfiguration represents a declarative configuration of the RHOS type for use
// with apply.
type RHOSApplyConfiguration struct {
	// InstanceType represents the Redhat Openstack instance type of the gateway node that will be
	// created on the managed cluster.
	// The default value is `PnTAE.CPU_4_Memory_8192_Disk_50`.
	InstanceType *string `json:"instanceType,omitempty"`
}

// RHOSApplyConfiguration constructs a declarative configuration of the RHOS type for use with
// apply.
func RHOS() *RHOSApplyConfiguration {
	return &RHOSApplyConfiguration{}
}

// WithInstanceType sets the InstanceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceType field is set to the value of the last call.
func (b *RHOSApplyConfiguration) WithInstanceType(value string) *RHOSApplyConfiguration {
	b.InstanceType = &value
	return b
}
