// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// SubmarinerConfigSpecApplyConfiguration represents a declarative configuration of the SubmarinerConfigSpec type for use
// with apply.
//
// SubmarinerConfigSpec describes the configuration of the Submariner.
type SubmarinerConfigSpecApplyConfiguration struct {
	// CableDriver represents the submariner cable driver implementation.
	// Available options are libreswan (default) strongswan, wireguard, and vxlan.
	CableDriver *string `json:"cableDriver,omitempty"`
	// GlobalCIDR specifies the global CIDR used by the cluster.
	GlobalCIDR *string `json:"globalCIDR,omitempty"`
	// IPSecIKEPort represents IPsec IKE port (default 500).
	IPSecIKEPort *int `json:"IPSecIKEPort,omitempty"`
	// IPSecNATTPort represents IPsec NAT-T port (default 4500).
	IPSecNATTPort *int `json:"IPSecNATTPort,omitempty"`
	// NATTDiscoveryPort specifies the port used for NAT-T Discovery (default UDP/4900).
	NATTDiscoveryPort *int `json:"NATTDiscoveryPort,omitempty"`
	// NATTEnable represents IPsec NAT-T enabled (default true).
	NATTEnable *bool `json:"NATTEnable,omitempty"`
	// AirGappedDeployment specifies that the cluster is in an air-gapped environment without access to external servers.
	AirGappedDeployment *bool `json:"airGappedDeployment,omitempty"`
	// LoadBalancerEnable enables or disables load balancer mode. When enabled, a LoadBalancer is created in the
	// submariner-operator namespace (default false).
	LoadBalancerEnable *bool `json:"loadBalancerEnable,omitempty"`
	// InsecureBrokerConnection disables certificate validation when contacting the broker.
	// This is useful for scenarios where the certificate chain isn't the same everywhere, e.g. with self-signed
	// certificates with a different trust chain in each cluster.
	InsecureBrokerConnection *bool `json:"insecureBrokerConnection,omitempty"`
	// HaltOnCertificateError halts pods on certificate errors (so they are restarted).
	HaltOnCertificateError *bool `json:"haltOnCertificateError,omitempty"`
	// HostedCluster enabled if the cluster is a hosted cluster.
	HostedCluster *bool `json:"hostedCluster,omitempty"`
	// IPSecDebug enables IPSec debugging.
	IPSecDebug *bool `json:"IPSecDebug,omitempty"`
	// ForceUDPEncaps forces UDP Encapsulation for IPSec.
	ForceUDPEncaps *bool `json:"forceUDPEncaps,omitempty"`
	// IPSecCertAuthMode enables certificate-based authentication mode for IPSec instead of PSK.
	IPSecCertAuthMode *bool `json:"IPSecCertAuthMode,omitempty"`
	// Debug enables Submariner debugging (in the logs).
	Debug *bool `json:"Debug,omitempty"`
	// CredentialsSecret is a reference to the secret with a certain cloud platform
	// credentials, the supported platform includes AWS, GCP, Azure, ROKS and OSD.
	// The submariner-addon will use these credentials to prepare Submariner cluster
	// environment. If the submariner cluster environment requires submariner-addon
	// preparation, this field should be specified.
	CredentialsSecret *v1.LocalObjectReference `json:"credentialsSecret,omitempty"`
	// SubscriptionConfig represents a Submariner subscription. SubscriptionConfig
	// can be used to customize the Submariner subscription.
	*SubscriptionConfigApplyConfiguration `json:"subscriptionConfig,omitempty"`
	// ImagePullSpecs represents the desired images of submariner components installed on the managed cluster.
	// If not specified, the default submariner images that was defined by submariner operator will be used.
	ImagePullSpecs *SubmarinerImagePullSpecsApplyConfiguration `json:"imagePullSpecs,omitempty"`
	// GatewayConfig represents the gateways configuration of the Submariner.
	*GatewayConfigApplyConfiguration `json:"gatewayConfig,omitempty"`
}

// SubmarinerConfigSpecApplyConfiguration constructs a declarative configuration of the SubmarinerConfigSpec type for use with
// apply.
func SubmarinerConfigSpec() *SubmarinerConfigSpecApplyConfiguration {
	return &SubmarinerConfigSpecApplyConfiguration{}
}

// WithCableDriver sets the CableDriver field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CableDriver field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithCableDriver(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.CableDriver = &value
	return b
}

// WithGlobalCIDR sets the GlobalCIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GlobalCIDR field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithGlobalCIDR(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.GlobalCIDR = &value
	return b
}

// WithIPSecIKEPort sets the IPSecIKEPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPSecIKEPort field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithIPSecIKEPort(value int) *SubmarinerConfigSpecApplyConfiguration {
	b.IPSecIKEPort = &value
	return b
}

// WithIPSecNATTPort sets the IPSecNATTPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPSecNATTPort field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithIPSecNATTPort(value int) *SubmarinerConfigSpecApplyConfiguration {
	b.IPSecNATTPort = &value
	return b
}

// WithNATTDiscoveryPort sets the NATTDiscoveryPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NATTDiscoveryPort field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithNATTDiscoveryPort(value int) *SubmarinerConfigSpecApplyConfiguration {
	b.NATTDiscoveryPort = &value
	return b
}

// WithNATTEnable sets the NATTEnable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NATTEnable field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithNATTEnable(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.NATTEnable = &value
	return b
}

// WithAirGappedDeployment sets the AirGappedDeployment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AirGappedDeployment field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithAirGappedDeployment(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.AirGappedDeployment = &value
	return b
}

// WithLoadBalancerEnable sets the LoadBalancerEnable field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancerEnable field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithLoadBalancerEnable(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.LoadBalancerEnable = &value
	return b
}

// WithInsecureBrokerConnection sets the InsecureBrokerConnection field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InsecureBrokerConnection field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithInsecureBrokerConnection(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.InsecureBrokerConnection = &value
	return b
}

// WithHaltOnCertificateError sets the HaltOnCertificateError field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HaltOnCertificateError field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithHaltOnCertificateError(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.HaltOnCertificateError = &value
	return b
}

// WithHostedCluster sets the HostedCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostedCluster field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithHostedCluster(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.HostedCluster = &value
	return b
}

// WithIPSecDebug sets the IPSecDebug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPSecDebug field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithIPSecDebug(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.IPSecDebug = &value
	return b
}

// WithForceUDPEncaps sets the ForceUDPEncaps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ForceUDPEncaps field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithForceUDPEncaps(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.ForceUDPEncaps = &value
	return b
}

// WithIPSecCertAuthMode sets the IPSecCertAuthMode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPSecCertAuthMode field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithIPSecCertAuthMode(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.IPSecCertAuthMode = &value
	return b
}

// WithDebug sets the Debug field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Debug field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithDebug(value bool) *SubmarinerConfigSpecApplyConfiguration {
	b.Debug = &value
	return b
}

// WithCredentialsSecret sets the CredentialsSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CredentialsSecret field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithCredentialsSecret(value v1.LocalObjectReference) *SubmarinerConfigSpecApplyConfiguration {
	b.CredentialsSecret = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithSource(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.ensureSubscriptionConfigApplyConfigurationExists()
	b.SubscriptionConfigApplyConfiguration.Source = &value
	return b
}

// WithSourceNamespace sets the SourceNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceNamespace field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithSourceNamespace(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.ensureSubscriptionConfigApplyConfigurationExists()
	b.SubscriptionConfigApplyConfiguration.SourceNamespace = &value
	return b
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithChannel(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.ensureSubscriptionConfigApplyConfigurationExists()
	b.SubscriptionConfigApplyConfiguration.Channel = &value
	return b
}

// WithStartingCSV sets the StartingCSV field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartingCSV field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithStartingCSV(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.ensureSubscriptionConfigApplyConfigurationExists()
	b.SubscriptionConfigApplyConfiguration.StartingCSV = &value
	return b
}

// WithInstallPlanApproval sets the InstallPlanApproval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallPlanApproval field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithInstallPlanApproval(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.ensureSubscriptionConfigApplyConfigurationExists()
	b.SubscriptionConfigApplyConfiguration.InstallPlanApproval = &value
	return b
}

func (b *SubmarinerConfigSpecApplyConfiguration) ensureSubscriptionConfigApplyConfigurationExists() {
	if b.SubscriptionConfigApplyConfiguration == nil {
		b.SubscriptionConfigApplyConfiguration = &SubscriptionConfigApplyConfiguration{}
	}
}

// WithImagePullSpecs sets the ImagePullSpecs field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ImagePullSpecs field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithImagePullSpecs(value *SubmarinerImagePullSpecsApplyConfiguration) *SubmarinerConfigSpecApplyConfiguration {
	b.ImagePullSpecs = value
	return b
}

// WithInstanceType sets the InstanceType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstanceType field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithInstanceType(value string) *SubmarinerConfigSpecApplyConfiguration {
	b.ensureAWSApplyConfigurationExists()
	b.AWSApplyConfiguration.InstanceType = &value
	return b
}

func (b *SubmarinerConfigSpecApplyConfiguration) ensureAWSApplyConfigurationExists() {
	if b.AWSApplyConfiguration == nil {
		b.AWSApplyConfiguration = &AWSApplyConfiguration{}
	}
}

func (b *SubmarinerConfigSpecApplyConfiguration) ensureGCPApplyConfigurationExists() {
	if b.GCPApplyConfiguration == nil {
		b.GCPApplyConfiguration = &GCPApplyConfiguration{}
	}
}

func (b *SubmarinerConfigSpecApplyConfiguration) ensureAzureApplyConfigurationExists() {
	if b.AzureApplyConfiguration == nil {
		b.AzureApplyConfiguration = &AzureApplyConfiguration{}
	}
}

func (b *SubmarinerConfigSpecApplyConfiguration) ensureRHOSApplyConfigurationExists() {
	if b.RHOSApplyConfiguration == nil {
		b.RHOSApplyConfiguration = &RHOSApplyConfiguration{}
	}
}

// WithGateways sets the Gateways field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Gateways field is set to the value of the last call.
func (b *SubmarinerConfigSpecApplyConfiguration) WithGateways(value int) *SubmarinerConfigSpecApplyConfiguration {
	b.ensureGatewayConfigApplyConfigurationExists()
	b.GatewayConfigApplyConfiguration.Gateways = &value
	return b
}

func (b *SubmarinerConfigSpecApplyConfiguration) ensureGatewayConfigApplyConfigurationExists() {
	if b.GatewayConfigApplyConfiguration == nil {
		b.GatewayConfigApplyConfiguration = &GatewayConfigApplyConfiguration{}
	}
}
