// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubmarinerImagePullSpecsApplyConfiguration represents a declarative configuration of the SubmarinerImagePullSpecs type for use
// with apply.
type SubmarinerImagePullSpecsApplyConfiguration struct {
	// SubmarinerImagePullSpec represents the desired image of submariner.
	SubmarinerImagePullSpec *string `json:"submarinerImagePullSpec,omitempty"`
	// LighthouseAgentImagePullSpec represents the desired image of the lighthouse agent.
	LighthouseAgentImagePullSpec *string `json:"lighthouseAgentImagePullSpec,omitempty"`
	// LighthouseCoreDNSImagePullSpec represents the desired image of lighthouse coredns.
	LighthouseCoreDNSImagePullSpec *string `json:"lighthouseCoreDNSImagePullSpec,omitempty"`
	// SubmarinerRouteAgentImagePullSpec represents the desired image of the submariner route agent.
	SubmarinerRouteAgentImagePullSpec *string `json:"submarinerRouteAgentImagePullSpec,omitempty"`
	// SubmarinerGlobalnetImagePullSpec represents the desired image of the submariner globalnet.
	SubmarinerGlobalnetImagePullSpec *string `json:"submarinerGlobalnetImagePullSpec,omitempty"`
	// SubmarinerNetworkPluginSyncerImagePullSpec represents the desired image of the submariner networkplugin syncer.
	// Deprecated: The networkplugin syncer was removed in v0.16.0.
	SubmarinerNetworkPluginSyncerImagePullSpec *string `json:"submarinerNetworkPluginSyncerImagePullSpec,omitempty"`
	// MetricsProxyImagePullSpec represents the desired image of the metrics proxy.
	MetricsProxyImagePullSpec *string `json:"metricsProxyImagePullSpec,omitempty"`
	// NettestImagePullSpec represents the desired image of nettest.
	NettestImagePullSpec *string `json:"nettestImagePullSpec,omitempty"`
}

// SubmarinerImagePullSpecsApplyConfiguration constructs a declarative configuration of the SubmarinerImagePullSpecs type for use with
// apply.
func SubmarinerImagePullSpecs() *SubmarinerImagePullSpecsApplyConfiguration {
	return &SubmarinerImagePullSpecsApplyConfiguration{}
}

// WithSubmarinerImagePullSpec sets the SubmarinerImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubmarinerImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithSubmarinerImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.SubmarinerImagePullSpec = &value
	return b
}

// WithLighthouseAgentImagePullSpec sets the LighthouseAgentImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LighthouseAgentImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithLighthouseAgentImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.LighthouseAgentImagePullSpec = &value
	return b
}

// WithLighthouseCoreDNSImagePullSpec sets the LighthouseCoreDNSImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LighthouseCoreDNSImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithLighthouseCoreDNSImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.LighthouseCoreDNSImagePullSpec = &value
	return b
}

// WithSubmarinerRouteAgentImagePullSpec sets the SubmarinerRouteAgentImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubmarinerRouteAgentImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithSubmarinerRouteAgentImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.SubmarinerRouteAgentImagePullSpec = &value
	return b
}

// WithSubmarinerGlobalnetImagePullSpec sets the SubmarinerGlobalnetImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubmarinerGlobalnetImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithSubmarinerGlobalnetImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.SubmarinerGlobalnetImagePullSpec = &value
	return b
}

// WithSubmarinerNetworkPluginSyncerImagePullSpec sets the SubmarinerNetworkPluginSyncerImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubmarinerNetworkPluginSyncerImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithSubmarinerNetworkPluginSyncerImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.SubmarinerNetworkPluginSyncerImagePullSpec = &value
	return b
}

// WithMetricsProxyImagePullSpec sets the MetricsProxyImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricsProxyImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithMetricsProxyImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.MetricsProxyImagePullSpec = &value
	return b
}

// WithNettestImagePullSpec sets the NettestImagePullSpec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NettestImagePullSpec field is set to the value of the last call.
func (b *SubmarinerImagePullSpecsApplyConfiguration) WithNettestImagePullSpec(value string) *SubmarinerImagePullSpecsApplyConfiguration {
	b.NettestImagePullSpec = &value
	return b
}
