// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// SubmarinerConfigStatusApplyConfiguration represents a declarative configuration of the SubmarinerConfigStatus type for use
// with apply.
//
// SubmarinerConfigStatus represents the current status of submariner configuration.
type SubmarinerConfigStatusApplyConfiguration struct {
	// Conditions contain the different condition statuses for this configuration.
	Conditions []v1.ConditionApplyConfiguration `json:"conditions,omitempty"`
	// ManagedClusterInfo represents the information of a managed cluster.
	ManagedClusterInfo *ManagedClusterInfoApplyConfiguration `json:"managedClusterInfo,omitempty"`
}

// SubmarinerConfigStatusApplyConfiguration constructs a declarative configuration of the SubmarinerConfigStatus type for use with
// apply.
func SubmarinerConfigStatus() *SubmarinerConfigStatusApplyConfiguration {
	return &SubmarinerConfigStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *SubmarinerConfigStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *SubmarinerConfigStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}

// WithManagedClusterInfo sets the ManagedClusterInfo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ManagedClusterInfo field is set to the value of the last call.
func (b *SubmarinerConfigStatusApplyConfiguration) WithManagedClusterInfo(value *ManagedClusterInfoApplyConfiguration) *SubmarinerConfigStatusApplyConfiguration {
	b.ManagedClusterInfo = value
	return b
}
