// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubscriptionConfigApplyConfiguration represents a declarative configuration of the SubscriptionConfig type for use
// with apply.
//
// SubscriptionConfig contains configuration specified for a submariner subscription.
type SubscriptionConfigApplyConfiguration struct {
	// Source represents the catalog source of a submariner subscription.
	// The default value is redhat-operators
	Source *string `json:"source,omitempty"`
	// SourceNamespace represents the catalog source namespace of a submariner subscription.
	// The default value is openshift-marketplace
	SourceNamespace *string `json:"sourceNamespace,omitempty"`
	// Channel represents the channel of a submariner subscription.
	Channel *string `json:"channel,omitempty"`
	// StartingCSV represents the startingCSV of a submariner subscription.
	StartingCSV *string `json:"startingCSV,omitempty"`
	// InstallPlanApproval determines whether subscription installation plans are applied automatically.
	InstallPlanApproval *string `json:"installPlanApproval,omitempty"`
}

// SubscriptionConfigApplyConfiguration constructs a declarative configuration of the SubscriptionConfig type for use with
// apply.
func SubscriptionConfig() *SubscriptionConfigApplyConfiguration {
	return &SubscriptionConfigApplyConfiguration{}
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *SubscriptionConfigApplyConfiguration) WithSource(value string) *SubscriptionConfigApplyConfiguration {
	b.Source = &value
	return b
}

// WithSourceNamespace sets the SourceNamespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceNamespace field is set to the value of the last call.
func (b *SubscriptionConfigApplyConfiguration) WithSourceNamespace(value string) *SubscriptionConfigApplyConfiguration {
	b.SourceNamespace = &value
	return b
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *SubscriptionConfigApplyConfiguration) WithChannel(value string) *SubscriptionConfigApplyConfiguration {
	b.Channel = &value
	return b
}

// WithStartingCSV sets the StartingCSV field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartingCSV field is set to the value of the last call.
func (b *SubscriptionConfigApplyConfiguration) WithStartingCSV(value string) *SubscriptionConfigApplyConfiguration {
	b.StartingCSV = &value
	return b
}

// WithInstallPlanApproval sets the InstallPlanApproval field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InstallPlanApproval field is set to the value of the last call.
func (b *SubscriptionConfigApplyConfiguration) WithInstallPlanApproval(value string) *SubscriptionConfigApplyConfiguration {
	b.InstallPlanApproval = &value
	return b
}
