// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerdiagnoseconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubmarinerDiagnoseConfigs implements SubmarinerDiagnoseConfigInterface
type FakeSubmarinerDiagnoseConfigs struct {
	Fake *FakeSubmarineraddonV1alpha1
	ns   string
}

var submarinerdiagnoseconfigsResource = v1alpha1.SchemeGroupVersion.WithResource("submarinerdiagnoseconfigs")

var submarinerdiagnoseconfigsKind = v1alpha1.SchemeGroupVersion.WithKind("SubmarinerDiagnoseConfig")

// Get takes name of the submarinerDiagnoseConfig, and returns the corresponding submarinerDiagnoseConfig object, and an error if there is any.
func (c *FakeSubmarinerDiagnoseConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(submarinerdiagnoseconfigsResource, c.ns, name), &v1alpha1.SubmarinerDiagnoseConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarinerDiagnoseConfig), err
}

// List takes label and field selectors, and returns the list of SubmarinerDiagnoseConfigs that match those selectors.
func (c *FakeSubmarinerDiagnoseConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubmarinerDiagnoseConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(submarinerdiagnoseconfigsResource, submarinerdiagnoseconfigsKind, c.ns, opts), &v1alpha1.SubmarinerDiagnoseConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SubmarinerDiagnoseConfigList{ListMeta: obj.(*v1alpha1.SubmarinerDiagnoseConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.SubmarinerDiagnoseConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested submarinerDiagnoseConfigs.
func (c *FakeSubmarinerDiagnoseConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(submarinerdiagnoseconfigsResource, c.ns, opts))

}

// Create takes the representation of a submarinerDiagnoseConfig and creates it.  Returns the server's representation of the submarinerDiagnoseConfig, and an error, if there is any.
func (c *FakeSubmarinerDiagnoseConfigs) Create(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.CreateOptions) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(submarinerdiagnoseconfigsResource, c.ns, submarinerDiagnoseConfig), &v1alpha1.SubmarinerDiagnoseConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarinerDiagnoseConfig), err
}

// Update takes the representation of a submarinerDiagnoseConfig and updates it. Returns the server's representation of the submarinerDiagnoseConfig, and an error, if there is any.
func (c *FakeSubmarinerDiagnoseConfigs) Update(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.UpdateOptions) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(submarinerdiagnoseconfigsResource, c.ns, submarinerDiagnoseConfig), &v1alpha1.SubmarinerDiagnoseConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarinerDiagnoseConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSubmarinerDiagnoseConfigs) UpdateStatus(ctx context.Context, submarinerDiagnoseConfig *v1alpha1.SubmarinerDiagnoseConfig, opts v1.UpdateOptions) (*v1alpha1.SubmarinerDiagnoseConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(submarinerdiagnoseconfigsResource, "status", c.ns, submarinerDiagnoseConfig), &v1alpha1.SubmarinerDiagnoseConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarinerDiagnoseConfig), err
}

// Delete takes name of the submarinerDiagnoseConfig and deletes it. Returns an error if one occurs.
func (c *FakeSubmarinerDiagnoseConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(submarinerdiagnoseconfigsResource, c.ns, name, opts), &v1alpha1.SubmarinerDiagnoseConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubmarinerDiagnoseConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(submarinerdiagnoseconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SubmarinerDiagnoseConfigList{})
	return err
}

// Patch applies the patch and returns the patched submarinerDiagnoseConfig.
func (c *FakeSubmarinerDiagnoseConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SubmarinerDiagnoseConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(submarinerdiagnoseconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.SubmarinerDiagnoseConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarinerDiagnoseConfig), err
}
