// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/stolostron/submariner-addon/pkg/apis/submarinerdiagnoseconfig/v1alpha1"
	submarinerdiagnoseconfigv1alpha1 "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/clientset/versioned/typed/submarinerdiagnoseconfig/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSubmarinerDiagnoseConfigs implements SubmarinerDiagnoseConfigInterface
type fakeSubmarinerDiagnoseConfigs struct {
	*gentype.FakeClientWithList[*v1alpha1.SubmarinerDiagnoseConfig, *v1alpha1.SubmarinerDiagnoseConfigList]
	Fake *FakeSubmarineraddonV1alpha1
}

func newFakeSubmarinerDiagnoseConfigs(fake *FakeSubmarineraddonV1alpha1, namespace string) submarinerdiagnoseconfigv1alpha1.SubmarinerDiagnoseConfigInterface {
	return &fakeSubmarinerDiagnoseConfigs{
		gentype.NewFakeClientWithList[*v1alpha1.SubmarinerDiagnoseConfig, *v1alpha1.SubmarinerDiagnoseConfigList](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("submarinerdiagnoseconfigs"),
			v1alpha1.SchemeGroupVersion.WithKind("SubmarinerDiagnoseConfig"),
			func() *v1alpha1.SubmarinerDiagnoseConfig { return &v1alpha1.SubmarinerDiagnoseConfig{} },
			func() *v1alpha1.SubmarinerDiagnoseConfigList { return &v1alpha1.SubmarinerDiagnoseConfigList{} },
			func(dst, src *v1alpha1.SubmarinerDiagnoseConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.SubmarinerDiagnoseConfigList) []*v1alpha1.SubmarinerDiagnoseConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.SubmarinerDiagnoseConfigList, items []*v1alpha1.SubmarinerDiagnoseConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
