// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/stolostron/submariner-addon/pkg/client/submarinerdiagnoseconfig/clientset/versioned/typed/submarinerdiagnoseconfig/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSubmarineraddonV1alpha1 struct {
	*testing.Fake
}

func (c *FakeSubmarineraddonV1alpha1) SubmarinerDiagnoseConfigs(namespace string) v1alpha1.SubmarinerDiagnoseConfigInterface {
	return newFakeSubmarinerDiagnoseConfigs(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSubmarineraddonV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
