// Code generated by MockGen. DO NOT EDIT.
// Source: ./client.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	compute "google.golang.org/api/compute/v1"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// DeleteFirewallRule mocks base method.
func (m *MockInterface) DeleteFirewallRule(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFirewallRule", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFirewallRule indicates an expected call of DeleteFirewallRule.
func (mr *MockInterfaceMockRecorder) DeleteFirewallRule(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFirewallRule", reflect.TypeOf((*MockInterface)(nil).DeleteFirewallRule), name)
}

// GetFirewallRule mocks base method.
func (m *MockInterface) GetFirewallRule(name string) (*compute.Firewall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirewallRule", name)
	ret0, _ := ret[0].(*compute.Firewall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirewallRule indicates an expected call of GetFirewallRule.
func (mr *MockInterfaceMockRecorder) GetFirewallRule(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirewallRule", reflect.TypeOf((*MockInterface)(nil).GetFirewallRule), name)
}

// GetProjectID mocks base method.
func (m *MockInterface) GetProjectID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProjectID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetProjectID indicates an expected call of GetProjectID.
func (mr *MockInterfaceMockRecorder) GetProjectID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProjectID", reflect.TypeOf((*MockInterface)(nil).GetProjectID))
}

// InsertFirewallRule mocks base method.
func (m *MockInterface) InsertFirewallRule(rule *compute.Firewall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertFirewallRule", rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertFirewallRule indicates an expected call of InsertFirewallRule.
func (mr *MockInterfaceMockRecorder) InsertFirewallRule(rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertFirewallRule", reflect.TypeOf((*MockInterface)(nil).InsertFirewallRule), rule)
}

// UpdateFirewallRule mocks base method.
func (m *MockInterface) UpdateFirewallRule(name string, rule *compute.Firewall) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFirewallRule", name, rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateFirewallRule indicates an expected call of UpdateFirewallRule.
func (mr *MockInterfaceMockRecorder) UpdateFirewallRule(name, rule interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFirewallRule", reflect.TypeOf((*MockInterface)(nil).UpdateFirewallRule), name, rule)
}
