apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: submariner
  namespace: {{ .InstallationNamespace }}
spec:
{{- if .CatalogChannel }}
  channel: {{ .CatalogChannel }}
{{- end}}
  installPlanApproval: {{ .InstallPlanApproval }}
  name: {{ .CatalogName }}
  source: {{ .CatalogSource }}
  sourceNamespace: {{ .CatalogSourceNamespace }}
{{- if .CatalogStartingCSV }}
  startingCSV: {{ .CatalogStartingCSV }}
{{- end}}
