apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: submariner-agent-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
priority: 1
readOnlyRootFilesystem: false
requiredDropCapabilities: []
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:serviceaccount:submariner-operator:submariner-operator
- system:serviceaccount:submariner-operator:submariner-lighthouse
- system:serviceaccount:submariner-operator:submariner-lighthouse-coredns
- system:serviceaccount:submariner-operator:submariner-gateway
- system:serviceaccount:submariner-operator:submariner-routeagent
- system:serviceaccount:submariner-operator:submariner-globalnet
- system:serviceaccount:submariner-operator:submariner-diagnose
volumes:
- '*'
