package v1alpha1

// This file contains a collection of methods that can be used from go-restful to
// generate Swagger API documentation for its models. Please read this PR for more
// information on the implementation: https://github.com/emicklei/go-restful/pull/215
//
// TODOs are ignored from the parser (e.g. TODO(andronat):... || TODO:...) if and only if
// they are on one line! For multiple line or blocks that you want to ignore use ---.
// Any context after a --- is ignored.
//
// Those methods can be generated by using hack/update-swagger-docs.sh

// AUTO-GENERATED FUNCTIONS START HERE
var map_SubmarinerDiagnoseConfig = map[string]string{
	"":       "SubmarinerDiagnoseConfig represents the configuration to run SubmarinerDiagnose Job.",
	"spec":   "Spec defines the configuration of the Submariner",
	"status": "Status represents the current status of SubmarinerDiagnose",
}

func (SubmarinerDiagnoseConfig) SwaggerDoc() map[string]string {
	return map_SubmarinerDiagnoseConfig
}

var map_SubmarinerDiagnoseConfigList = map[string]string{
	"":         "SubmarinerDiagnoseConfigList is a collection of SubmarinerDiagnoseConfig.",
	"metadata": "Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
	"items":    "Items is a list of SubmarinerDiagnoseConfig.",
}

func (SubmarinerDiagnoseConfigList) SwaggerDoc() map[string]string {
	return map_SubmarinerDiagnoseConfigList
}

var map_SubmarinerDiagnoseSpec = map[string]string{
	"": "SubmarinerDiagnoseSpec defines the desired configuration to run SubmarinerDiagnose.",
}

func (SubmarinerDiagnoseSpec) SwaggerDoc() map[string]string {
	return map_SubmarinerDiagnoseSpec
}

var map_SubmarinerDiagnoseStatus = map[string]string{
	"": "SubmarinerDiagnoseStatus defines the observed result of SubmarinerDiagnose.",
}

func (SubmarinerDiagnoseStatus) SwaggerDoc() map[string]string {
	return map_SubmarinerDiagnoseStatus
}

// AUTO-GENERATED FUNCTIONS END HERE
