//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallOptions) DeepCopyInto(out *FirewallOptions) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallOptions.
func (in *FirewallOptions) DeepCopy() *FirewallOptions {
	if in == nil {
		return nil
	}
	out := new(FirewallOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FirewallStatus) DeepCopyInto(out *FirewallStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FirewallStatus.
func (in *FirewallStatus) DeepCopy() *FirewallStatus {
	if in == nil {
		return nil
	}
	out := new(FirewallStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubmarinerDiagnoseConfig) DeepCopyInto(out *SubmarinerDiagnoseConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubmarinerDiagnoseConfig.
func (in *SubmarinerDiagnoseConfig) DeepCopy() *SubmarinerDiagnoseConfig {
	if in == nil {
		return nil
	}
	out := new(SubmarinerDiagnoseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubmarinerDiagnoseConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubmarinerDiagnoseConfigList) DeepCopyInto(out *SubmarinerDiagnoseConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SubmarinerDiagnoseConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubmarinerDiagnoseConfigList.
func (in *SubmarinerDiagnoseConfigList) DeepCopy() *SubmarinerDiagnoseConfigList {
	if in == nil {
		return nil
	}
	out := new(SubmarinerDiagnoseConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SubmarinerDiagnoseConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubmarinerDiagnoseSpec) DeepCopyInto(out *SubmarinerDiagnoseSpec) {
	*out = *in
	out.FirewallOptions = in.FirewallOptions
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubmarinerDiagnoseSpec.
func (in *SubmarinerDiagnoseSpec) DeepCopy() *SubmarinerDiagnoseSpec {
	if in == nil {
		return nil
	}
	out := new(SubmarinerDiagnoseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubmarinerDiagnoseStatus) DeepCopyInto(out *SubmarinerDiagnoseStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.FirewallStatus = in.FirewallStatus
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubmarinerDiagnoseStatus.
func (in *SubmarinerDiagnoseStatus) DeepCopy() *SubmarinerDiagnoseStatus {
	if in == nil {
		return nil
	}
	out := new(SubmarinerDiagnoseStatus)
	in.DeepCopyInto(out)
	return out
}
